find_path(HTTPMOCKSERVER_INCLUDE_DIR
          NAMES httpmockserver/mock_server.h)

find_library(HTTPMOCKSERVER_LIBRARY
             NAMES httpmockserver
             HINTS ${HTTPMOCKSERVER_LIBRARY_ROOT})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(HTTPMOCKSERVER REQUIRED_VARS HTTPMOCKSERVER_LIBRARY HTTPMOCKSERVER_INCLUDE_DIR)

if(HTTPMOCKSERVER_FOUND)
    set(HTTPMOCKSERVER_LIBRARIES ${HTTPMOCKSERVER_LIBRARY} microhttpd CACHE INTERNAL "")
    set(HTTPMOCKSERVER_INCLUDE_DIRS ${HTTPMOCKSERVER_INCLUDE_DIR} CACHE INTERNAL "")
endif()