name: Doc

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y doxygen graphviz

    - name: Run doxygen
      working-directory: ${{github.workspace}}/doc
      run: doxygen Doxyfile

    - name: Deploy to GitHub pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: ${{github.workspace}}/doc/html
